# Generated by Django 3.2.18 on 2023-03-13 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20230313_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 14, 40, 54, 646867)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='sw71jjbbkwy3qa53', max_length=100),
        ),
    ]
