# Generated by Django 3.2.18 on 2023-03-17 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_auto_20230313_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerequest',
            name='act',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 11, 4, 55, 475082)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='tbfh0r6q58ba5q36', max_length=100),
        ),
    ]
