# Generated by Django 3.2.18 on 2023-05-01 21:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_auto_20230317_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintrades',
            name='scurrency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellcurrency', to='exchange.cp_currencies'),
        ),
        migrations.AlterField(
            model_name='protrades',
            name='bcurrency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='probuycurrency', to='exchange.cp_currencies'),
        ),
        migrations.AlterField(
            model_name='protrades',
            name='scurrency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prosellcurrency', to='exchange.cp_currencies'),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 21, 19, 57, 85981)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='fvy2c24acpjtxb61', max_length=100),
        ),
    ]
