# Generated by Django 3.2.18 on 2023-05-01 21:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_auto_20230501_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintrades',
            name='bcurrency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buycurrency', to='exchange.cp_currencies'),
        ),
        migrations.AlterField(
            model_name='maintrades',
            name='scurrency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellcurrency', to='exchange.currencies'),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 21, 47, 7, 135049)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='et7azv1m09akjg75', max_length=100),
        ),
    ]
