# Generated by Django 3.2.18 on 2023-05-07 21:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_auto_20230501_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintrades',
            name='image',
            field=models.ImageField(null=True, upload_to='main_trades'),
        ),
        migrations.AlterField(
            model_name='maintrades',
            name='scurrency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sellcurrency', to='exchange.currencies'),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 21, 55, 13, 994814)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='3vkr6gjgn3ekkx43', max_length=100),
        ),
    ]
