# Generated by Django 3.2.18 on 2023-05-07 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_auto_20230507_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 21, 58, 13, 989090)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='satxcsx16c798r17', max_length=100),
        ),
    ]
