# Generated by Django 3.2.18 on 2023-05-08 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_auto_20230507_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintrades',
            old_name='image',
            new_name='b_image',
        ),
        migrations.AddField(
            model_name='maintrades',
            name='s_image',
            field=models.ImageField(null=True, upload_to='main_trades'),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 11, 13, 14, 162161)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='5v29v24a196s4n06', max_length=100),
        ),
    ]
