# Generated by Django 3.2.18 on 2023-05-09 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_auto_20230508_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintradesbuyorder',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintradessellorder',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 18, 16, 42, 977740)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='a3qja8z27ertj410', max_length=100),
        ),
    ]
