# Generated by Django 3.2.18 on 2023-05-09 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_auto_20230509_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintradesbuyorder',
            name='done',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='maintradessellorder',
            name='done',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 18, 27, 21, 328807)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='r2t4je9v8fkng257', max_length=100),
        ),
    ]
