# Generated by Django 3.2.18 on 2023-05-09 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_auto_20230509_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintradesbuyorder',
            old_name='done',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='maintradessellorder',
            old_name='done',
            new_name='left',
        ),
        migrations.RemoveField(
            model_name='maintradesbuyorder',
            name='start',
        ),
        migrations.RemoveField(
            model_name='maintradessellorder',
            name='start',
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 18, 49, 19, 967140)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='tjc13pgebsfcf030', max_length=100),
        ),
    ]
