# Generated by Django 3.2.18 on 2023-05-09 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0013_auto_20230509_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 18, 49, 44, 759524)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='z10eftyzbbp74m42', max_length=100),
        ),
    ]
