# Generated by Django 3.2.18 on 2023-05-22 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0015_auto_20230509_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='USDTpercent3',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 20, 44, 48, 17350)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='2d2fzrrackn54e73', max_length=100),
        ),
    ]
