# Generated by Django 3.2.18 on 2023-05-22 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0016_auto_20230522_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='sellpercent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 22, 19, 50, 163595)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='4xgdnmptmgkdpm44', max_length=100),
        ),
    ]
