# Generated by Django 3.2.18 on 2023-06-04 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0017_auto_20230522_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general',
            name='name',
        ),
        migrations.AddField(
            model_name='general',
            name='en_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='general',
            name='en_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='general',
            name='fa_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='general',
            name='fa_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 8, 11, 23, 913935)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='w2cevvf16ew54b50', max_length=100),
        ),
    ]
