# Generated by Django 3.2.18 on 2023-06-04 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0018_auto_20230604_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottomsticker',
            name='img',
        ),
        migrations.RemoveField(
            model_name='topsticker',
            name='text',
        ),
        migrations.RemoveField(
            model_name='topsticker',
            name='title',
        ),
        migrations.AddField(
            model_name='bottomsticker',
            name='icon',
            field=models.FileField(max_length=30, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='topsticker',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='bottomsticker',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bottomsticker',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 9, 28, 58, 922494)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='xbnynbt9b2fgqa32', max_length=100),
        ),
    ]
