# Generated by Django 3.2.18 on 2023-06-04 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0019_auto_20230604_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomsticker',
            name='icon',
            field=models.FileField(null=True, upload_to='main_page'),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 9, 32, 59, 764793)),
        ),
        migrations.AlterField(
            model_name='topsticker',
            name='img',
            field=models.ImageField(null=True, upload_to='main_page'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='6c45c5jdw7mkww73', max_length=100),
        ),
    ]
