# Generated by Django 3.2.18 on 2023-06-04 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0020_auto_20230604_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 9, 34, 11, 881890)),
        ),
        migrations.AlterField(
            model_name='topsticker',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='t6tczgrra49jt860', max_length=100),
        ),
    ]
