# Generated by Django 3.2.18 on 2023-06-04 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0021_auto_20230604_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomsticker',
            name='icon',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 10, 20, 30, 96315)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='c3vjy4asb9r9b834', max_length=100),
        ),
    ]
