# Generated by Django 3.2.18 on 2023-06-04 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0022_auto_20230604_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='leverage',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 11, 50, 40, 331533)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='7zga0qc6wwgx8r61', max_length=100),
        ),
    ]
