# Generated by Django 3.2.18 on 2023-06-04 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0023_auto_20230604_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leverage',
            old_name='price',
            new_name='change',
        ),
        migrations.AddField(
            model_name='leverage',
            name='last',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leverage',
            name='rial',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 11, 53, 17, 455178)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='2dcpb1a598aa0058', max_length=100),
        ),
    ]
