# Generated by Django 3.2.18 on 2023-06-04 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0024_auto_20230604_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='leverage',
            name='volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 12, 38, 29, 783870)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='ezry2ms1gd2d6g85', max_length=100),
        ),
    ]
