# Generated by Django 3.2.18 on 2023-06-04 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0025_auto_20230604_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leverage',
            name='volume',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 12, 54, 16, 453178)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='ssm05mep8aa2a132', max_length=100),
        ),
    ]
