# Generated by Django 3.2.18 on 2023-06-04 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0026_auto_20230604_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='minitext',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 13, 3, 29, 942197)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='c4amcneyk0w3d587', max_length=100),
        ),
    ]
