# Generated by Django 3.2.18 on 2023-06-04 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0029_auto_20230604_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='leverage',
            name='fa_symbol',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 13, 59, 10, 788064)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='enppeq9s9kejq215', max_length=100),
        ),
    ]
