# Generated by Django 3.2.18 on 2023-06-04 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0030_auto_20230604_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leverage',
            name='buymax',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leverage',
            name='buymin',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leverage',
            name='sellmax',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leverage',
            name='sellmin',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 14, 16, 33, 907769)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='r4pwbz0kvwq7p307', max_length=100),
        ),
    ]
