# Generated by Django 3.2.18 on 2023-06-04 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0031_auto_20230604_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leverage',
            name='buymax',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='leverage',
            name='buymin',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='leverage',
            name='sellmax',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='leverage',
            name='sellmin',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 14, 17, 23, 751254)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='crs4cmqazdy80a27', max_length=100),
        ),
    ]
