# Generated by Django 3.2.18 on 2023-06-05 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0032_auto_20230604_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 8, 17, 50, 705794)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='qk8zsffmb2rn4553', max_length=100),
        ),
    ]
