# Generated by Django 3.2.18 on 2023-06-24 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0034_auto_20230619_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionid',
            name='ids',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 19, 30, 56, 753663)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='zekbw878p7yhvj71', max_length=100),
        ),
    ]
