# Generated by Django 3.2.18 on 2023-06-24 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0035_auto_20230624_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionid',
            name='ids',
        ),
        migrations.AddField(
            model_name='transactionid',
            name='transactionid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 19, 37, 37, 668820)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='6z5f5jcm1ra9z735', max_length=100),
        ),
    ]
