# Generated by Django 3.2.18 on 2023-06-24 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0036_auto_20230624_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionid',
            old_name='transactionid',
            new_name='tid',
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 19, 40, 18, 570701)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='meaxmgxp94v2hg05', max_length=100),
        ),
    ]
