# Generated by Django 3.2.18 on 2023-06-24 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0037_auto_20230624_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 19, 43, 16, 277499)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='ptjys55bb08zse69', max_length=100),
        ),
    ]
