# Generated by Django 3.2.18 on 2023-06-24 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0039_auto_20230624_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 19, 44, 58, 494143)),
        ),
        migrations.AlterField(
            model_name='transactionid',
            name='tid',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='j587k0w169t2gv85', max_length=100),
        ),
    ]
