# Generated by Django 3.2.18 on 2023-06-24 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0040_auto_20230624_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionid',
            name='tid',
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 19, 45, 31, 742376)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='4q5h7r1j90atd102', max_length=100),
        ),
    ]
