# Generated by Django 3.2.18 on 2023-06-24 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0041_auto_20230624_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionid',
            name='tid',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 19, 45, 43, 110112)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='acjgav266etfbt57', max_length=100),
        ),
    ]
