# Generated by Django 3.2.18 on 2023-06-25 18:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0042_auto_20230624_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 18, 32, 57, 326108)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='sgpvnvanwdpqdq62', max_length=100),
        ),
        migrations.CreateModel(
            name='P2Prequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('balance', models.FloatField()),
                ('minimum_amount', models.FloatField()),
                ('maximum_time', models.IntegerField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2ps', to='exchange.cp_currencies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2ps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
