# Generated by Django 3.2.18 on 2023-06-25 19:35

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0043_auto_20230625_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2prequest',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 19, 35, 37, 937789)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='53s2jk4wy31e6362', max_length=100),
        ),
    ]
