# Generated by Django 3.2.18 on 2023-06-26 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0044_auto_20230625_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2prequest',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 12, 34, 31, 648147)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='gk1r8jk9q594yq40', max_length=100),
        ),
    ]
