# Generated by Django 3.2.18 on 2023-07-01 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0045_auto_20230626_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2prequest',
            name='change_world',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='p2prequest',
            name='limit_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='p2prequest',
            name='limit_min',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='p2prequest',
            name='limit_world',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 1, 19, 42, 43, 240483)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='98jb9t3r27xrra71', max_length=100),
        ),
    ]
