# Generated by Django 3.2.18 on 2023-07-04 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0046_auto_20230701_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2prequest',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 8, 22, 11, 852010)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='0me3xfc686jmcx83', max_length=100),
        ),
    ]
