# Generated by Django 3.2.18 on 2023-07-04 08:22

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0047_auto_20230704_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2prequest',
            name='rid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 8, 22, 33, 531813)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='pcj09st5bzdxdp98', max_length=100),
        ),
    ]
