# Generated by Django 3.2.18 on 2023-07-04 08:25

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0049_auto_20230704_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2prequest',
            name='rid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 8, 25, 56, 941717)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='9wbrm3d7yv8bx395', max_length=100),
        ),
    ]
