# Generated by Django 3.2.18 on 2023-07-04 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0050_auto_20230704_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 8, 27, 0, 354897)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='7f7xt4a0rhx90013', max_length=100),
        ),
    ]
