# Generated by Django 3.2.18 on 2023-07-04 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0051_auto_20230704_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p2prequest',
            name='rid',
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 8, 42, 13, 944471)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='72h2ay2ezxd8bh38', max_length=100),
        ),
    ]
