# Generated by Django 3.2.18 on 2023-07-04 08:43

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0052_auto_20230704_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p2prequest',
            name='id',
        ),
        migrations.AddField(
            model_name='p2prequest',
            name='rid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 8, 43, 13, 286355)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='rzg7spjsp6hzfk05', max_length=100),
        ),
    ]
