# Generated by Django 3.2.18 on 2023-07-05 10:57

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0055_auto_20230705_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p2pbuyrequest',
            name='id',
        ),
        migrations.AddField(
            model_name='p2pbuyrequest',
            name='rid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 10, 57, 55, 799230)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='26862bbbt627zp52', max_length=100),
        ),
    ]
