# Generated by Django 3.2.18 on 2023-07-05 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0056_auto_20230705_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2pbuyrequest',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 11, 14, 15, 571129)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='56n1rv2adyz79584', max_length=100),
        ),
    ]
