# Generated by Django 3.2.18 on 2023-07-05 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0059_auto_20230705_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='wallet',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 19, 13, 16, 825062)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='zwgy92gsdgefcx76', max_length=100),
        ),
    ]
