# Generated by Django 3.2.18 on 2023-07-05 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0060_auto_20230705_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='details',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='memo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 20, 45, 33, 816039)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='418ch4w1rxgs2d31', max_length=100),
        ),
    ]
