# Generated by Django 3.2.18 on 2023-07-05 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0063_auto_20230705_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 21, 26, 7, 556275)),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 21, 26, 7, 556536)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='qx5rtppaq0nxfe55', max_length=100),
        ),
    ]
