# Generated by Django 3.2.18 on 2023-07-05 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0064_auto_20230705_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='details',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='wallet',
        ),
        migrations.AddField(
            model_name='p2pbuyrequest',
            name='details',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='p2pbuyrequest',
            name='memo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='p2pbuyrequest',
            name='wallet',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='smscode',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 21, 51, 19, 779036)),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 21, 51, 19, 779392)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='efscyvjxgcxv3k37', max_length=100),
        ),
    ]
