# Generated by Django 3.2.18 on 2023-07-06 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0065_auto_20230705_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2pbuyrequest',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smscode',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 8, 28, 7, 484501)),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 8, 28, 7, 484792)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='vvct26mpv172a931', max_length=100),
        ),
    ]
