# Generated by Django 4.2.3 on 2023-07-06 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0066_auto_20230706_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 13, 5, 8, 894396)),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 13, 5, 8, 894756)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='69fpd8bssc9eq725', max_length=100),
        ),
    ]
